"""
Reason codes for entitlement / playback authorization decisions.

Shared by EntitlementService and PlaybackAuthorizationService so that deny
responses carry a stable, machine-readable code (never a secret).
"""
from enum import Enum


class ReasonCode(str, Enum):
    ALLOW = "ALLOW"

    SUBSCRIBER_NOT_FOUND = "SUBSCRIBER_NOT_FOUND"
    SUBSCRIBER_SUSPENDED = "SUBSCRIBER_SUSPENDED"
    SUBSCRIBER_DISABLED = "SUBSCRIBER_DISABLED"

    SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND"
    SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED"
    SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"
    SUBSCRIPTION_SUSPENDED = "SUBSCRIPTION_SUSPENDED"

    PLAN_INACTIVE = "PLAN_INACTIVE"

    DEVICE_NOT_REGISTERED = "DEVICE_NOT_REGISTERED"
    DEVICE_BLOCKED = "DEVICE_BLOCKED"

    CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND"
    CHANNEL_INACTIVE = "CHANNEL_INACTIVE"
    CHANNEL_NOT_INCLUDED = "CHANNEL_NOT_INCLUDED"
